version: '3.4'

services:
  
  productapiservices:
    image: ${DOCKER_REGISTRY-}productapiservices
    build:
      context: .
      dockerfile: ProductAPIServices/Dockerfile


  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile


  
  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: WebMvc/Dockerfile

